# Configuration file for Travis continuous integration.
# See https://travis-ci.org/apache/calcite
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
language: java
matrix:
  fast_finish: true
  include:
    - env: IMAGE=maven:3-jdk-10
    - env: IMAGE=maven:3-jdk-9
    - env: IMAGE=maven:3-jdk-8
branches:
  only:
    - master
    - new-master
    - javadoc
    - /^branch-.*$/
    - /^[0-9]+-.*$/
env:
  global:
  - DOCKERRUN="docker run -it --rm -v $PWD:/src -v $HOME/.m2:/root/.m2 -w /src"
services:
  - docker
before_install:
  - docker pull $IMAGE
install:
  # Print the Maven version, skip tests and javadoc
  - $DOCKERRUN $IMAGE mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Djavax.net.ssl.trustStorePassword=changeit -B -V
script:
  # Print surefire output to the console instead of files
  - unset _JAVA_OPTIONS
  - $DOCKERRUN $IMAGE mvn -Dsurefire.useFile=false -Dsurefire.parallel= -Djavax.net.ssl.trustStorePassword=changeit test
git:
  depth: 10000
sudo: required
cache:
  directories:
    - $HOME/.m2
# End .travis.yml
